"""Add production readiness fields and indexes

Revision ID: 7948b37d8d3b
Revises: 391bcb8cec2e
Create Date: 2026-08-02 23:14:09.888117

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7948b37d8d3b"
down_revision: str | None = "391bcb8cec2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agencies", sa.Column("logo_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "agencies",
        sa.Column("registration_number", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_agencies_created_at"), "agencies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_agencies_registration_number"),
        "agencies",
        ["registration_number"],
        unique=False,
    )
    op.add_column(
        "leads",
        sa.Column("status_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "leads", sa.Column("follow_up_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_leads_created_at"), "leads", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_leads_follow_up_date"), "leads", ["follow_up_date"], unique=False
    )
    op.add_column(
        "scholarships",
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "scholarships", sa.Column("currency", sa.String(length=10), nullable=True)
    )
    op.create_index(
        op.f("ix_scholarships_created_at"), "scholarships", ["created_at"], unique=False
    )
    op.add_column(
        "student_profiles",
        sa.Column("profile_picture_url", sa.String(length=500), nullable=True),
    )
    op.alter_column(
        "student_profiles",
        "budget",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_student_profiles_created_at"),
        "student_profiles",
        ["created_at"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("failed_login_attempts", sa.Integer(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_column("users", "password_changed_at")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failed_login_attempts")
    op.drop_column("users", "last_login")
    op.drop_index(op.f("ix_student_profiles_created_at"), table_name="student_profiles")
    op.alter_column(
        "student_profiles",
        "budget",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("student_profiles", "profile_picture_url")
    op.drop_index(op.f("ix_scholarships_created_at"), table_name="scholarships")
    op.drop_column("scholarships", "currency")
    op.drop_column("scholarships", "amount")
    op.drop_index(op.f("ix_leads_follow_up_date"), table_name="leads")
    op.drop_index(op.f("ix_leads_created_at"), table_name="leads")
    op.drop_column("leads", "follow_up_date")
    op.drop_column("leads", "status_updated_at")
    op.drop_index(op.f("ix_agencies_registration_number"), table_name="agencies")
    op.drop_index(op.f("ix_agencies_created_at"), table_name="agencies")
    op.drop_column("agencies", "registration_number")
    op.drop_column("agencies", "logo_url")
    # ### end Alembic commands ###
