"""Init models

Revision ID: 391bcb8cec2e
Revises:
Create Date: 2026-08-02 23:02:47.527679

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "391bcb8cec2e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scholarships",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("university", sa.String(length=255), nullable=True),
        sa.Column(
            "degree_level",
            sa.Enum(
                "HIGH_SCHOOL",
                "BACHELOR",
                "MASTER",
                "PHD",
                "POSTDOC",
                "OTHER",
                name="degreelevel",
            ),
            nullable=False,
        ),
        sa.Column(
            "funding_type",
            sa.Enum(
                "FULLY_FUNDED",
                "PARTIAL",
                "TUITION_FEE_ONLY",
                "SELF_FUNDED",
                name="fundingtype",
            ),
            nullable=False,
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("application_link", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scholarships_country"), "scholarships", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_scholarships_deadline"), "scholarships", ["deadline"], unique=False
    )
    op.create_index(op.f("ix_scholarships_id"), "scholarships", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("STUDENT", "AGENCY", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "agencies",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("agency_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="agencyverificationstatus"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_agencies_country"), "agencies", ["country"], unique=False)
    op.create_index(op.f("ix_agencies_email"), "agencies", ["email"], unique=False)
    op.create_index(op.f("ix_agencies_id"), "agencies", ["id"], unique=False)
    op.create_index(
        op.f("ix_agencies_verification_status"),
        "agencies",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "student_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="gender"),
            nullable=True,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("highest_qualification", sa.String(length=255), nullable=True),
        sa.Column("cgpa_or_percentage", sa.Float(), nullable=True),
        sa.Column(
            "preferred_degree",
            sa.Enum(
                "HIGH_SCHOOL",
                "BACHELOR",
                "MASTER",
                "PHD",
                "POSTDOC",
                "OTHER",
                name="degreelevel",
            ),
            nullable=True,
        ),
        sa.Column("preferred_country", sa.String(length=100), nullable=True),
        sa.Column("budget", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_student_profiles_country"),
        "student_profiles",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_profiles_id"), "student_profiles", ["id"], unique=False
    )
    op.create_table(
        "leads",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("agency_id", sa.String(length=36), nullable=True),
        sa.Column("scholarship_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "CONTACTED", "IN_PROGRESS", "WON", "LOST", name="leadstatus"
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["scholarship_id"], ["scholarships.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["student_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_id"), "leads", ["id"], unique=False)
    op.create_index(op.f("ix_leads_status"), "leads", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leads_status"), table_name="leads")
    op.drop_index(op.f("ix_leads_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_student_profiles_id"), table_name="student_profiles")
    op.drop_index(op.f("ix_student_profiles_country"), table_name="student_profiles")
    op.drop_table("student_profiles")
    op.drop_index(op.f("ix_agencies_verification_status"), table_name="agencies")
    op.drop_index(op.f("ix_agencies_id"), table_name="agencies")
    op.drop_index(op.f("ix_agencies_email"), table_name="agencies")
    op.drop_index(op.f("ix_agencies_country"), table_name="agencies")
    op.drop_table("agencies")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_scholarships_id"), table_name="scholarships")
    op.drop_index(op.f("ix_scholarships_deadline"), table_name="scholarships")
    op.drop_index(op.f("ix_scholarships_country"), table_name="scholarships")
    op.drop_table("scholarships")
    # ### end Alembic commands ###
