"""add_application_requirements

Revision ID: 2dd6e2e4b4b6
Revises: 7703e93a37d8
Create Date: 2026-08-18 13:19:16.645005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd6e2e4b4b6'
down_revision: Union[str, None] = '7703e93a37d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarship_application_requirements',
    sa.Column('scholarship_id', sa.String(length=36), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_application_requirements_created_at'), 'scholarship_application_requirements', ['created_at'], unique=False)
    op.create_index(op.f('ix_scholarship_application_requirements_id'), 'scholarship_application_requirements', ['id'], unique=False)
    op.create_table('student_application_responses',
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['scholarship_application_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_application_responses_created_at'), 'student_application_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_application_responses_id'), 'student_application_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_application_responses_id'), table_name='student_application_responses')
    op.drop_index(op.f('ix_student_application_responses_created_at'), table_name='student_application_responses')
    op.drop_table('student_application_responses')
    op.drop_index(op.f('ix_scholarship_application_requirements_id'), table_name='scholarship_application_requirements')
    op.drop_index(op.f('ix_scholarship_application_requirements_created_at'), table_name='scholarship_application_requirements')
    op.drop_table('scholarship_application_requirements')
    # ### end Alembic commands ###
