"""Add S3 fields to student documents

Revision ID: f014d705e0cd
Revises: 6bb1150c69cc
Create Date: 2026-08-17 17:16:35.900882

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f014d705e0cd'
down_revision: str | None = '6bb1150c69cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_documents', sa.Column('s3_key', sa.String(length=500), nullable=False))
    op.add_column('student_documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('student_documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_documents', 'mime_type')
    op.drop_column('student_documents', 'file_size')
    op.drop_column('student_documents', 's3_key')
    # ### end Alembic commands ###
