"""create_bookmarks_table

Revision ID: 7eba73e83858
Revises: f014d705e0cd
Create Date: 2026-08-17 21:50:19.480479

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7eba73e83858'
down_revision: str | None = 'f014d705e0cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('student_profile_id', sa.String(length=36), nullable=False),
    sa.Column('bookmark_type', sa.String(length=50), nullable=False),
    sa.Column('scholarship_id', sa.String(length=36), nullable=True),
    sa.Column('university_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'scholarship_id', name='uq_student_scholarship_bookmark'),
    sa.UniqueConstraint('student_profile_id', 'university_id', name='uq_student_university_bookmark')
    )
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
